### ISSUE TITLE
default admin password 

### ISSUE THREAD

**Issue by hsafe** [devinsolutions/docker-taiga#12]
Hi,
I used your docker-compose in advanced mode to bring up the taiga, everything worked out of the box for a test env I set up for it, however default taiga admin user password i.e 123123 did not work. I tried to look for it in all the files config settings there are no place I could find it. Can you state where in the code you set it and  how to find it please?
Thanks

**Comment by raphaelwdrf** [comment]
remember to populate-db, and remember to change taiga-back/setting.py ALLOWED_HOSTS.

Like this to allow all:
ALLOWED_HOSTS = [
    '*',
]

**Comment by lubo** [comment]
Hi @hsafe. Please, see [Populate the database with initial data](https://github.com/devinsolutions/docker-taiga/blob/5dc3ebfacd50d8335016c998e4a176291ac5561f/README.md#populate-the-database-with-initial-data) and [line 50 in docker-compose.advanced.yml](https://github.com/devinsolutions/docker-taiga/blob/5dc3ebfacd50d8335016c998e4a176291ac5561f/docker-compose.advanced.yml#L50). Also, please don't modify `ALLOWED_HOSTS` as @KinGsNowGH suggested unless you know what you're doing.

**Comment by hsafe** [comment]
@lubo Thanks, got it Cheers
