### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by gabrieletassoni** [devinsolutions/docker-taiga#14]
Is there a documented way for installing in this image the `taiga-contrib-ldap-auth-ext` python package (or any other taiga extension) and configure the local.py as [documented](https://github.com/Monogramm/taiga-contrib-ldap-auth-ext) in the extension page?

I tried to manually install using docker exec on a running instance, but it fails:

`docker exec -it abs-taiga_server pip install taiga-contrib-ldap-auth-ext`

With this error log:

`ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/taiga'
Check the permissions.`

Thank you for the help, bye,
gabriele

**Comment by lubo** [comment]
Hi @gabrieletassoni. There's no way that's specific to this image, just do it like you would with any other image - create your own! Of course, you don't have to do it from scratch, something like this should cover your needs:

```dockerfile
FROM devinsolutions/taiga:<tag-of-your-choice>
USER root  # Our image uses `taiga` user, which cannot alter the system in any way
RUN …  # Do your thing here
USER taiga  # DON'T FORGET TO DROP THE PRIVILEGES!
```

Check out our `Dockerfile` to find out more about how we do things, you might find that useful. Anyway, I think this answers the question, so I'm closing this issue. Feel free to ask more questions if there's something you don't understand about this image. If you find a real problem, which prevents you from building on top of our image, we can reopen. Hope this helps.
