### ISSUE TITLE
Deprecation notice on dockerhub?

### ISSUE THREAD

**Issue by ibotty** [devinsolutions/docker-taiga#18]
Hi!

Is the image deprecated?  It says so on dockerhub, but is the best maintained taiga image by far.  (I also like, that it uses less privileges.  Thank you for building it)

Cheers

**Comment by lubo** [comment]
Hi @ibotty. Yes we're deprecating the image in #17 as Devin Solutions no longer uses Taiga. I'm very glad to hear you like the image and I'm very sorry we won't be able to help you out anymore. But, this repository will stay public and you can always start your own fork if you wanna keep the party going. :slightly_smiling_face: 

I'm closing this issue as I believe your question is answered, but don't hesitate to reply if there's more you wanna know. :slightly_smiling_face:
