### ISSUE TITLE
django admin static files

### ISSUE THREAD

**Issue by jwaes** [devinsolutions/docker-taiga#5]
Hi, i am trying your container. I use a slightly altered version of your docker-compose.yml .
Anyway setup went fine. I want to add regular users. Therefor i go to the /admin django admin page. But there the static content (css, js) is unavailable.

This post is about the same issue and there is a reply marked as a solution:
https://stackoverflow.com/questions/7241688/django-admin-css-missing/11299269

I added
`STATIC_ROOT = 'static'`
to my settings.py file, but i cannot go on
```
jaco@myserver~/projects/private-repo/taiga $ sudo docker exec -it  taiga_app_1  sh
/opt/taiga-back $ python manage.py collectstatic
Trying import local.py settings...
Copying '/usr/local/lib/python3.7/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Traceback (most recent call last):
...
PermissionError: [Errno 13] Permission denied: '/opt/taiga-back/static'
```
Isn't this something that should be done in the dockerfile ?

**Comment by lubo** [comment]
Hi. Setting `STATIC_ROOT` isn't necessary as it's already set in `/opt/taiga-back/settings/local.py`. Also, `collectstatic` is being run as part of `run-server` command. No, from the nature of these files, it shouldn't be run in Dockerfile and you just need to restart your container if the static files need to be recollected. It sounds like there's something wrong with your configuration, but I can't help you with the information you've provided. Therefore, I'm closing the issue, but I'll reopen it if you prove there's actually something wrong with the image. If you provide more information, I might be able to help you.

**Comment by jwaes** [comment]
Thanks for you swift reply.

I had a look at the local.py you referenced and found the solution to my issue

I added

```
MEDIA_URL = "media/"
STATIC_URL = "/static/"
```

to my settings.py

local.py file has absolute path `http://localhost:8080/static/` hardcoded

**Comment by lubo** [comment]
If you take a look at [/etc/opt/taiga-back/settings.py](https://github.com/devinsolutions/docker-taiga/blob/abbabee427f123652d51f28def4c34b685f2e1f0/root/etc/opt/taiga-back/settings.py#L31), there's actually a comment explaining why these should be absolute URLs.

**Comment by jwaes** [comment]
Thnx
