### ISSUE TITLE
username and login

### ISSUE THREAD

**Issue by lphuard** [devinsolutions/docker-taiga#7]
After fresh install on vps with ubuntu 18.04 lts - login screen shows - but can not login with default admin 123123 (not sure this works on your version) and can not sign up. Getting the error message.

**Comment by lubo** [comment]
Hi @lphuard. I'd recommend you to read the README before deploying the image. There's [Populate the database with initial data](https://github.com/devinsolutions/docker-taiga#populate-the-database-with-initial-data) section, which talks about the problem.

If that doesn't solve your problem, I'll reopen the issue.
